datadirectory="D:/yüksek lisans/Thesis/bioluminescens" # directory where data file is
datafilename="p_series_48h.csv" #CSV datafile
#times in the first column, data in subsequent columns
#first row is asumed to be sample names
# (for the corresponding column) of the form name_replicate# ..ie Bmal_2
outputfilename="Lum_U2OS_TW_NonToxic_20uM_10uM_20221228_output.csv"
permax=32 #Max acceptable period - periods generated by waveclock greater than this are ignored
permin=20 #Min acceptable period - periods generated by waveclock less than this are ignored
library(waveclock)
#setwd(datadirectory)


#############
read.tcsv = function(file, header=TRUE, sep=",", ...) {
  
  n = max(count.fields(file, sep=sep), na.rm=TRUE)
  x = readLines(file)
  
  .splitvar = function(x, sep, n) {
    var = unlist(strsplit(x, split=sep))
    length(var) = n
    return(var)
  }
  
  x = do.call(cbind, lapply(x, .splitvar, sep=sep, n=n))
  x = apply(x, 1, paste, collapse=sep) 
  out = read.csv(text=x, sep=sep, header=header, ...)
  return(out)
  
}
##########


data = read.tcsv(datafilename, header=TRUE, row.names=1,sep=";")

library(lubridate)



timelist<-as.numeric(hour(hms(as.character(rownames(data))))+minute(hms(as.character(rownames(data))))/60+second(hms(as.character(rownames(data))))/3600)

hourlist<-timelist

#hourlist<-24*timelist
deltatime<-(timelist[2]-timelist[1])
basedir=getwd()
#Plot the raw data
dir.create("DataPlots")
setwd("DataPlots")



for(i in 1:dim(data)[2]){
  filename=paste("graph_",names(data)[i],".jpeg",sep="")
  jpeg(file=filename)
  plot(as.numeric(timelist/24), data[,i], col="blue",ylim=c((0.9*min(data)),( 1.1* max(data))), xlab="time(days)", ylab="counts/sec")
  dev.off()
}

###############################
setwd(basedir)
dir.create("WavePlots")
setwd("WavePlots")
############################
#Define a table to dunk the output into
output = matrix(NA,nr=dim(data)[2],nc=7)
colnames( output ) <- c(
  "median (midpoint)",
  "median (lower limit)",
  "median (upper limit)",
  "mean (midpoint)",
  "mean (lower limit)",
  "mean (upper limit)",
  "mean")
row.names(output)<-names(data)
#Iterate through a data file
for(i in 1:dim(data)[2]){
  sd=1
  loop_flag=TRUE
  set.seed(1)
  while ((loop_flag ==TRUE) & (sd<50)){
    filename=paste("waveplot_num",i,".jpeg",sep="")
    jpeg(file=filename)
    sd=sd+1
    local_timeseries<-ts(data[,i],start=0, deltat = deltatime )
    local_results<-waveclock(local_timeseries,cfamily.args = list( ptile = 0.005, bstep = 5, nbchain = 5000 ))
    row<-which(local_results$modes$index =="Total")
    period<-local_results$modes$"median (midpoint)"[row]
    if (length(period)!=0) {loop_flag=FALSE}
    dev.off()
  }
  if( !is.null( local_results$modes ) ){
    output[i,] = unlist( local_results$modes[1,2:8] )}
}
amplist<-c()
meanlist<-c()
#fullmeanlist<-c()
perlist<-c()
for(i in 1:dim(data)[2]){
  local_dependant<-data[,i] #kinetic series to fit
  local_independant<-hourlist #the factor included because the time in the data file is in days
  #and period is given in hours
  maxtime=max(local_independant)
  local_period=output[i,1] #wavelet determined period
  if(is.na(local_period)|((local_period<permin)|(local_period>permax))){ # if no determined period or period outside range
    local_period=NA # set period as not determined
    keep_times<-which((local_independant>24) & (local_independant< (maxtime-24))) # stil exclude 1st and last day of date
    local_amp=NA # if no fit period no amp is calculate
    local_mean=mean(local_dependant[keep_times]) # baseline is just mean of included data
  }
  else{ # if period acceptabe
    keep_times<-which((local_independant>local_period) & (local_independant< (maxtime-local_period))) # exclude first and last cycle
    local_independant<-local_independant[keep_times]
    local_dependant<-local_dependant[keep_times]
    sindep<-sin(2*pi*(local_independant/local_period))
    cosdep<-cos(2*pi*(local_independant/local_period))
    fitmodel=lm(local_dependant ~ cosdep + sindep ) #fit to cosinor model
    local_mean=as.vector(fitmodel$coefficients[1])
    cos_coef=as.vector(fitmodel$coefficients[2])
    sin_coef=as.vector(fitmodel$coefficients[3])
    local_amp=(cos_coef^2+sin_coef^2)^(1/2)
  }
  amplist<-append(amplist,local_amp)
  meanlist<-append(meanlist,local_mean)
  perlist<-append(perlist,local_period)
}
outputframe=data.frame(output)
outputframe$Amp<-as.vector(amplist)
outputframe$Baseline<-as.vector(meanlist)
outputframe$Period<-as.vector(perlist)
#outputframe$FullBaseline<-as.vector(fullmeanlist)
setwd(datadirectory)
write.csv(outputframe,outputfilename)
